### ISSUE TITLE
where to change the UI access port config

### ISSUE THREAD

**Issue by wanghaisheng** [vmware/harbor#190]
in default it is 80, but i want to change into 808
```
[wanghs@db2 Deploy]$ cat docker-compose.yml
version: '2'
services:
  log:
    build: ./log/
    volumes:
      - /var/log/harbor/:/var/log/docker/
    ports:
      - 1514:514
  registry:
    image: library/registry:2.4.0
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5002:5001
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "registry"
  mysql:
    build: ./db/
    volumes:
      - /data/database:/var/lib/mysql
    env_file:
      - ./config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "mysql"
  ui:
    build:
      context: ../
      dockerfile: Dockerfile.ui
    env_file:
      - ./config/ui/env
    volumes:
      - ./config/ui/app.conf:/etc/ui/app.conf
      - ./config/ui/private_key.pem:/etc/ui/private_key.pem
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "ui"
  proxy:
    image: library/nginx:1.9
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 808:80
      - 443:443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "proxy"

```

**Comment by reasonerjt** [comment]
@wanghaisheng 
I see you know how to update the port in docker-compose.yml, so what's your expectation?

**Comment by wanghaisheng** [comment]
@reasonerjt  my server could not let any other machine to access 80 port ,then i could not access through 808 either. i want to know why

**Comment by int32bit** [comment]
It's better to make it configurable in `harbor.cfg` ?

**Comment by wanghaisheng** [comment]
really i find nowhere in harbor.cfg to change this config

**Comment by frank798** [comment]
you can change ui port follow this:
1、edit app.conf in /harbor/config/ui,you can see current runmode=dev and the port set for dev is 80,you can change this value to whatever you need
2、edit nginx.conf in /harbor/config/nginx,edit port in "upstream ui"
3、restart harbor

**Comment by wanghaisheng** [comment]
@frank798  you mean no need to change anything in docker-compose.yml?
```
[wanghs@db2 Deploy]$ cat docker-compose.yml
version: '2'
services:
  log:
    build: ./log/
    volumes:
      - /var/log/harbor/:/var/log/docker/
    ports:
      - 1514:514
  registry:
    image: library/registry:2.4.0
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5002:5001
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "registry"
  mysql:
    build: ./db/
    volumes:
      - /data/database:/var/lib/mysql
    env_file:
      - ./config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "mysql"
  ui:
    build:
      context: ../
      dockerfile: Dockerfile.ui
    env_file:
      - ./config/ui/env
    volumes:
      - ./config/ui/app.conf:/etc/ui/app.conf
      - ./config/ui/private_key.pem:/etc/ui/private_key.pem
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "ui"
  proxy:
    image: library/nginx:1.9
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 808:808
      - 443:443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "proxy"

```

```
[wanghs@db2 Deploy]$ cat templates/ui/app.conf
appname = registry
runmode = dev

[lang]
types = en-US|zh-CN|de-DE
names = en-US|zh-CN|de-DE

[dev]
httpport = 808

[mail]
host = $email_server
port = $email_server_port
username = $email_username
password = $email_password
from = $email_from
ssl = $email_ssl
```

```
[wanghs@db2 Deploy]$ cat config/nginx/nginx.conf
worker_processes auto;

events {
  worker_connections 1024;
  use epoll;
  multi_accept on;
}

http {
  tcp_nodelay on;

  # this is necessary for us to be able to disable request buffering in all cases
  proxy_http_version 1.1;


  upstream registry {
    server registry:5000;
  }

  upstream ui {
    server ui:808;
  }


  server {
    listen 80;

    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    location / {
      proxy_pass http://ui/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;
    }

    location /v1/ {
      return 404;
    }

    location /v2/ {
      proxy_pass http://registry/v2/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;

    }

    location /service/ {
      proxy_pass http://ui/service/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;
    }
  }
}

```

**Comment by frank798** [comment]
@wanghaisheng yes! Nothing to change in docker-compose.yml, your nginx listen in 80 port ,  this port is used by nginx, should be change also,if you can't use 80 in anywhere. In my env,nginx listen in 443.

**Comment by wanghaisheng** [comment]
1、edit app.conf in /harbor/config/ui,you can see current runmode=dev and the port set for dev is 80,you can change this value to whatever you need
you mean 
```
[wanghs@db2 Deploy]$ cat templates/ui/app.conf
appname = registry
runmode = dev

[lang]
types = en-US|zh-CN|de-DE
names = en-US|zh-CN|de-DE

[dev]
httpport = 80

[mail]
host = $email_server
port = $email_server_port
username = $email_username
password = $email_password
from = $email_from
ssl = $email_ssl

```

**Comment by wanghaisheng** [comment]
now  
config/nginx/nginx.conf
```
[wanghs@db2 Deploy]$ cat config/nginx/nginx.conf
worker_processes auto;

events {
  worker_connections 1024;
  use epoll;
  multi_accept on;
}

http {
  tcp_nodelay on;

  # this is necessary for us to be able to disable request buffering in all cases
  proxy_http_version 1.1;


  upstream registry {
    server registry:5000;
  }

  upstream ui {
    server ui:808;
  }


  server {
    listen 808;

    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    location / {
      proxy_pass http://ui/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;
    }

    location /v1/ {
      return 404;
    }

    location /v2/ {
      proxy_pass http://registry/v2/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;

    }

    location /service/ {
      proxy_pass http://ui/service/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;
    }
  }
}

```
templates/ui/app.conf
```
[wanghs@db2 Deploy]$ cat templates/ui/app.conf
appname = registry
runmode = dev

[lang]
types = en-US|zh-CN|de-DE
names = en-US|zh-CN|de-DE

[dev]
httpport = 808

[mail]
host = $email_server
port = $email_server_port
username = $email_username
password = $email_password
from = $email_from
ssl = $email_ssl

```
harbor.cfg
```
[wanghs@db2 Deploy]$ cat harbor.cfg
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = 192.168.27.236

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = http

#Email account settings for sending out password resetting emails.
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The password of Harbor admin, change this before any production use.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#The basedn template to look up a user in LDAP and verify the user's password.
ldap_basedn = uid=%s,ou=people,dc=mydomain,dc=com

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Turn on or off the self-registration feature
self_registration = on

#Turn on or off the customize your certicate
customize_crt = on

#fill in your certicate message
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com
#####
```
docker-compose.yml keep as orginal

nope 
http://192.168.27.236:808/
https://192.168.27.236/
 does not work 
```
[wanghs@db2 Deploy]$ docker-compose up --force-recreate
Recreating deploy_log_1
Recreating deploy_ui_1
Recreating deploy_registry_1
Recreating deploy_mysql_1
Recreating deploy_proxy_1
Attaching to deploy_log_1, deploy_registry_1, deploy_mysql_1, deploy_ui_1, deploy_proxy_1
registry_1  | time="2016-05-06T02:35:45.950687005Z" level=info msg="debug server listening localhost:5001"
mysql_1     | 2016-05-06 02:35:49 0 [Note] mysqld (mysqld 5.6.30) starting as process 1 ...
registry_1  | time="2016-05-06T02:35:47.681657791Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=d7f76224-0c57-4fb5-bdc5-37f4d94d4e7d service=registry version=v2.4.0
registry_1  | time="2016-05-06T02:35:47.681916483Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=d7f76224-0c57-4fb5-bdc5-37f4d94d4e7d service=registry version=v2.4.0
registry_1  | time="2016-05-06T02:35:47.713911526Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=d7f76224-0c57-4fb5-bdc5-37f4d94d4e7d service=registry version=v2.4.0
mysql_1     | 2016-05-06 02:35:49 1 [Note] Plugin 'FEDERATED' is disabled.
registry_1  | time="2016-05-06T02:35:47.71440544Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=d7f76224-0c57-4fb5-bdc5-37f4d94d4e7d service=registry version=v2.4.0
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
ui_1        | 2016-05-06T02:35:47Z [INFO] Config path: /etc/ui/app.conf
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: The InnoDB memory heap is disabled
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
registry_1  | time="2016-05-06T02:35:47.714509059Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=d7f76224-0c57-4fb5-bdc5-37f4d94d4e7d service=registry version=v2.4.0
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Memory barrier is not used
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Using Linux native AIO
ui_1        | 2016-05-06T02:35:47Z [DEBUG] [base.go:73]: db url: mysql:3306, db user: root
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Using CPU crc32 instructions
ui_1        | 2016-05-06T02:35:47Z [ERROR] [base.go:85]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Completed initialization of buffer pool
ui_1        | 2016-05-06T02:35:49Z [ERROR] [base.go:85]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.4:3306: getsockopt: connection refused
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: The log sequence numbers 1706898 and 1706898 in ibdata files do not match the log sequence number 1706918 in the ib_logfiles!
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Database was not shutdown normally!
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Starting crash recovery.
ui_1        | 2016-05-06T02:35:53Z [INFO] User id: 1 already has its encrypted password.
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Reading tablespace information from the .ibd files...
ui_1        | 2016/05/06 02:35:53 [asm_amd64.s:1998][I] http server Running on :808
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: Restoring possible half-written data pages
mysql_1     | 2016-05-06 02:35:49 1 [Note] InnoDB: from the doublewrite buffer...
mysql_1     | 2016-05-06 02:35:51 1 [Note] InnoDB: 128 rollback segment(s) are active.
mysql_1     | 2016-05-06 02:35:51 1 [Note] InnoDB: Waiting for purge to start
mysql_1     | 2016-05-06 02:35:51 1 [Note] InnoDB: 5.6.30 started; log sequence number 1706918
mysql_1     | 2016-05-06 02:35:51 1 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1     | 2016-05-06 02:35:51 1 [Note] IPv6 is available.
mysql_1     | 2016-05-06 02:35:51 1 [Note]   - '::' resolves to '::';
mysql_1     | 2016-05-06 02:35:51 1 [Note] Server socket created on IP: '::'.
mysql_1     | 2016-05-06 02:35:51 1 [Warning] 'proxies_priv' entry '@ root@0279669c0397' ignored in --skip-name-resolve mode.
mysql_1     | 2016-05-06 02:35:51 1 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 2016-05-06 02:35:51 1 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.6.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)

```

```
[wanghs@db2 mantl]$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
b65218014cc7        library/nginx:1.9        "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   deploy_proxy_1
bda9e6740364        deploy_ui                "/go/bin/harbor_ui"      2 minutes ago       Up 2 minutes        80/tcp                                     deploy_ui_1
ddff1248ce3a        deploy_mysql             "docker-entrypoint.sh"   2 minutes ago       Up 2 minutes        3306/tcp                                   deploy_mysql_1
93660d01eff0        library/registry:2.4.0   "/bin/registry serve "   2 minutes ago       Up 2 minutes        5000/tcp, 0.0.0.0:5001->5001/tcp           deploy_registry_1
71f5ff512696        deploy_log               "/bin/sh -c 'cron && "   2 minutes ago       Up 2 minutes        0.0.0.0:1514->514/tcp                      deploy_log_1

```

**Comment by wanghaisheng** [comment]
fix this by the following steps
if you just want to change WEB UI access port  for example 80-->808 here
1.change config in  config/nginx/nginx.conf
```
[wanghs@db2 Deploy]$ cat config/nginx/nginx.conf
worker_processes auto;

events {
  worker_connections 1024;
  use epoll;
  multi_accept on;
}

http {
  tcp_nodelay on;

  # this is necessary for us to be able to disable request buffering in all cases
  proxy_http_version 1.1;


  upstream registry {
    server registry:5000;
  }

  upstream ui {
    **server ui:808**;
  }


  server {
    **listen 808**;

    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    location / {
      proxy_pass http://ui/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;
    }

    location /v1/ {
      return 404;
    }

    location /v2/ {
      proxy_pass http://registry/v2/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;

    }

    location /service/ {
      proxy_pass http://ui/service/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_buffering off;
      proxy_request_buffering off;
    }
  }
}

```
2. change config here 
templates/ui/app.conf
```
[wanghs@db2 Deploy]$ cat templates/ui/app.conf
appname = registry
runmode = dev

[lang]
types = en-US|zh-CN|de-DE
names = en-US|zh-CN|de-DE

[dev]
**httpport = 808**

[mail]
host = $email_server
port = $email_server_port
username = $email_username
password = $email_password
from = $email_from
ssl = $email_ssl

```
3. change config here 
harbor.cfg
```
[wanghs@db2 Deploy]$ cat harbor.cfg
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
**hostname = 192.168.27.236**

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = http

#Email account settings for sending out password resetting emails.
email_server = smtp.mydomain.com
email_server_port = 25
email_username = sample_admin@mydomain.com
email_password = abc
email_from = admin <sample_admin@mydomain.com>
email_ssl = false

##The password of Harbor admin, change this before any production use.
harbor_admin_password = Harbor12345

##By default the auth mode is db_auth, i.e. the credentials are stored in a local database.
#Set it to ldap_auth if you want to verify a user's credentials against an LDAP server.
auth_mode = db_auth

#The url for an ldap endpoint.
ldap_url = ldaps://ldap.mydomain.com

#The basedn template to look up a user in LDAP and verify the user's password.
ldap_basedn = uid=%s,ou=people,dc=mydomain,dc=com

#The password for the root user of mysql db, change this before any production use.
db_password = root123

#Turn on or off the self-registration feature
self_registration = on

#Turn on or off the customize your certicate
customize_crt = on

#fill in your certicate message
crt_country = CN
crt_state = State
crt_location = CN
crt_organization = organization
crt_organizationalunit = organizational unit
crt_commonname = example.com
crt_email = example@example.com
#####
```
4.at last 
docker-compose.yml 
```
[wanghs@db2 Deploy]$ cat docker-compose.yml
version: '2'
services:
  log:
    build: ./log/
    volumes:
      - /var/log/harbor/:/var/log/docker/
    ports:
      - 1514:514
  registry:
    image: library/registry:2.4.0
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "registry"
  mysql:
    build: ./db/
    volumes:
      - /data/database:/var/lib/mysql
    env_file:
      - ./config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "mysql"
  ui:
    build:
      context: ../
      dockerfile: Dockerfile.ui
    env_file:
      - ./config/ui/env
    volumes:
      - ./config/ui/app.conf:/etc/ui/app.conf
      - ./config/ui/private_key.pem:/etc/ui/private_key.pem
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "ui"
  proxy:
    image: library/nginx:1.9
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      **- 808:808**
      - 443:443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        syslog-tag: "proxy"

```

```
[wanghs@db2 Deploy]$ docker-compose up
Starting deploy_log_1
Starting deploy_ui_1
Starting deploy_registry_1
Starting deploy_mysql_1
Starting deploy_proxy_1
Attaching to deploy_log_1, deploy_ui_1, deploy_mysql_1, deploy_registry_1, deploy_proxy_1
ui_1        | 2016-05-06T02:47:57Z [INFO] Config path: /etc/ui/app.conf
mysql_1     | 2016-05-06 02:47:58 0 [Note] mysqld (mysqld 5.6.30) starting as process 1 ...
ui_1        | 2016-05-06T02:47:57Z [DEBUG] [base.go:73]: db url: mysql:3306, db user: root
ui_1        | 2016-05-06T02:47:58Z [ERROR] [base.go:85]: failed to connect to db, retry after 2 seconds :dial tcp 172.18.0.5:3306: getsockopt: connection refused
mysql_1     | 2016-05-06 02:47:58 1 [Note] Plugin 'FEDERATED' is disabled.
registry_1  | time="2016-05-06T02:47:59.350241225Z" level=info msg="debug server listening localhost:5001"
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: The InnoDB memory heap is disabled
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Memory barrier is not used
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
registry_1  | time="2016-05-06T02:47:59.351967426Z" level=info msg="configuring endpoint harbor (http://ui/service/notifications), timeout=500ms, headers=map[]" go.version=go1.6.1 instance.id=409d7080-baa5-4669-914a-81477efbc151 service=registry version=v2.4.0
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Using Linux native AIO
registry_1  | time="2016-05-06T02:47:59.3520647Z" level=info msg="redis not configured" go.version=go1.6.1 instance.id=409d7080-baa5-4669-914a-81477efbc151 service=registry version=v2.4.0
registry_1  | time="2016-05-06T02:47:59.385303819Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.6.1 instance.id=409d7080-baa5-4669-914a-81477efbc151 service=registry version=v2.4.0
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Using CPU crc32 instructions
registry_1  | time="2016-05-06T02:47:59.385832975Z" level=debug msg="configured \"token\" access controller" go.version=go1.6.1 instance.id=409d7080-baa5-4669-914a-81477efbc151 service=registry version=v2.4.0
registry_1  | time="2016-05-06T02:47:59.385957578Z" level=info msg="listening on [::]:5000" go.version=go1.6.1 instance.id=409d7080-baa5-4669-914a-81477efbc151 service=registry version=v2.4.0
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Completed initialization of buffer pool
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: The log sequence numbers 1706928 and 1706928 in ibdata files do not match the log sequence number 1706938 in the ib_logfiles!
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Database was not shutdown normally!
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Starting crash recovery.
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Reading tablespace information from the .ibd files...
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Restoring possible half-written data pages
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: from the doublewrite buffer...
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: 128 rollback segment(s) are active.
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: Waiting for purge to start
mysql_1     | 2016-05-06 02:47:58 1 [Note] InnoDB: 5.6.30 started; log sequence number 1706938
mysql_1     | 2016-05-06 02:47:58 1 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1     | 2016-05-06 02:47:58 1 [Note] IPv6 is available.
mysql_1     | 2016-05-06 02:47:58 1 [Note]   - '::' resolves to '::';
mysql_1     | 2016-05-06 02:47:58 1 [Note] Server socket created on IP: '::'.
mysql_1     | 2016-05-06 02:47:58 1 [Warning] 'proxies_priv' entry '@ root@0279669c0397' ignored in --skip-name-resolve mode.
mysql_1     | 2016-05-06 02:47:58 1 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 2016-05-06 02:47:58 1 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.6.30'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
ui_1        | 2016-05-06T02:48:00Z [INFO] User id: 1 already has its encrypted password.
ui_1        | 2016/05/06 02:48:00 [asm_amd64.s:1998][I] http server Running on :808
```


then you can access through
http://192.168.27.236:808/
