### ISSUE TITLE
How to specify the database information for harbor-ui 

### ISSUE THREAD

**Issue by shencan** [vmware/harbor#2292]
I want to use AWS RDS replace local db(harbor-db). I specify RDS information with docker-compose environment. after harbor-ui  running . I can found environment information with `env` commad. but  harbor-ui  program not use these env. the error log (mysql HOST use mysql)
```
May 11 20:37:08 ip-172-18-0-1.ec2.internal ui[3864]: 2017-05-11T12:37:08Z [ERROR] [utils.go:94]: failed to connect to tcp://mysql:3306, retry after 2 seconds :dial tcp: lookup mysql: no such host
```

the docker-compose for  harbor-ui  environment.
```
  ui:
    image: vmware/harbor-ui:v1.1.1-rc4
    container_name: harbor-ui
    environment:
      - MYSQL_HOST=xxxx.us-east-1.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_USR=xxx
      - MYSQL_PWD=yyy
    env_file:
      - ./common/config/ui/env
    restart: always
    volumes:
      - ./common/config/ui/app.conf:/etc/ui/app.conf:z
      - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
    networks:
      - harbor
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
```
