### ISSUE TITLE
Unable to delete images with Openstack Swift as the storage backend

### ISSUE THREAD

**Issue by analbeard** [vmware/harbor#2854]
docker-engine: 17.06.0~ce-0~ubuntu
relevant log files: https://gist.github.com/analbeard/fca3ddfb36d3e8ba0f71dce1cd13acdf

We are running Harbor with an on-premise Openstack Swift cluster providing the storage - push/pull works fine but we are unable to delete images. The swift user has full read/write permissions on the container and I can manually delete test files. Please see above for the log files for the transaction.

Storage configuration:
```
storage:
  swift:
    username: registry
    password: **
    authurl: https://auth.storage.domain.com/v2.0
    tenant: **
    region: ** 
    container: dockerimages
    delete:
        enabled: true
```

**Comment by ywk253100** [comment]
According to the docs of docker distribution, swift has no property called "delete". You should set "delete" in the same level with "swift".

 ```
storage:
  swift:
    username: registry
    password: **
    authurl: https://auth.storage.domain.com/v2.0
    tenant: **
    region: ** 
    container: dockerimages
  delete:
    enabled: true
```
