### ISSUE TITLE
Clair http proxy

### ISSUE THREAD

**Issue by roldancer** [vmware/harbor#3107]
Hi All, Is there any way to configure a http/https proxy for the Clair service via harbor.cfg ?

Thanks

**Comment by everydaynerd** [comment]
Wow, funny I have been working on this all day, and have not seen a way to do this.  I've tried modifying the docker-compose.clair.yml file and adding:
`
    env_file:
      ./common/config/clair/proxy_env
`
and then adding in the proxy information in that proxy_env file like this:
`
HTTP_PROXY=http://proxyserveraddress:8080
HTTPS_PROXY=http://proxyserveraddress:8080
http_proxy=http://proxyserveraddress:8080
https_proxy=http://proxyserveraddress:8080
`

I've also tried to add just a `environment:` tag in the compose file, and defining `http_proxy` & `https_proxy` there, but to no avail.

**Comment by cbarzu** [comment]
Hi everybody,

for me editing the docker-compose.clair.yml as follow did the trick:

```
 clair:
    networks:
      - harbor-clair
    container_name: clair
    image: vmware/clair:v2.0.1-photon
    restart: always
    environment:
      HTTP_PROXY: "http://my-proxy.com:80"
      HTTPS_PROXY: "https://my-proxy.com:80"
```

Regards,
Claudiu
