### ISSUE TITLE
Use Ingress in Kubernetes deploy instead of proxy(nginx)

### ISSUE THREAD

**Issue by rockwyc992** [vmware/harbor#3611]
Ingress is the recommend way to proxy your traffic into Kubernetes cluster.  

We could define a ingress yaml like this

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: harbor-proxy
spec:
  rules:
  - host: harbor.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
      - path: /v2
        backend:
          serviceName: registry
          servicePort: repo
      - path: /service
        backend:
          serviceName: ui
          servicePort: 80
```
