### ISSUE TITLE
[Bug] [Kubernetes] ConfigMap volume mount on worng path

### ISSUE THREAD

**Issue by rockwyc992** [vmware/harbor#3637]
There is a path on [registry.rc.yaml](https://github.com/vmware/harbor/blob/master/make/kubernetes/registry/registry.rc.yaml#L25) is different from [registry/Dockerfile](https://github.com/vmware/harbor/blob/master/make/photon/registry/Dockerfile#L26).

``` yaml
# registry.rc.yaml
volumeMounts:
- mountPath: /etc/docker/registry
```

``` Dockerfile
# Dockerfile
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/etc/registry/config.yml"]
```

It would cause that registry cannot configure everything correctly (like storage.filesystem.rootdirectory).

So that, I will loss my image when I restart my container at other machine in Kubernetes cluster.
