### ISSUE TITLE
docker swarm compose stack error: No such image: xx

### ISSUE THREAD

**Issue by jeremy-gao** [vmware/harbor#3824]
I have successfully run the harbor, and successfully enabled https. 
I can successfully execute the following command:

```shell
docker pull xxx.harbor.com/lelai/php:7.0-swoole
```
However, when I use the compose yaml file deployment, I can not read the image file:

```shell
[root@docker-machine-host1 ~]# docker stack deploy --compose-file docker-xx.yaml test
Creating service test_gateway1
[root@docker-machine-host1 ~]# docker service ps test_gateway1 
ID                  NAME                  IMAGE                  NODE                   DESIRED STATE       CURRENT STATE            ERROR                              PORTS
96cgde8qxphv        test_gateway1.1       lelai/php:7.0-swoole   docker-machine-host2   Ready               Rejected 3 seconds ago   "No such image: lelai/php:7.0-…"   
o4qkicj1hw98         \_ test_gateway1.1   lelai/php:7.0-swoole   docker-machine-host2   Shutdown            Rejected 3 seconds ago   "No such image: lelai/php:7.0-…"
```

my compose yaml file content:

```yaml
version: "3.2"
services:
  gateway1:
    image: lelai/php:7.0-swoole 
    networks:
      - swoole_net
    volumes:
      - type: bind
        source: /home/
        target: /home/
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      mode: replicated
      replicas: 1
      
networks:
  swoole_net:
    external: true

```

```shell
[root@docker-machine-host1 ~]# cat /etc/docker/daemon.json 
{
  "registry-mirrors": ["https://xxx.harbor.com"]
}
```

Have any friends met this problem?

**Comment by wy65701436** [comment]
we didn't try mirror much, I think you can refer to https://docs.docker.com/registry/recipes/mirror/#configure-the-docker-daemon. 

You can try to modify the yml to xxx.harbor.com/lelai/php:7.0-swoole.

**Comment by jeremy-gao** [comment]
@wy65701436   Thank you for your reply, my question is actually want to know, when the harbor docker as a private registry, how to use docker-compose to read harbor inside the image? I have set before `registry-mirrors`, but not pull. If the direct implementation of the `docker pull` command is available from harbor in normal to the image.

**Comment by wy65701436** [comment]
@jeremy-gao I am not clear understand your question. 

If you want to tell docker to pull image from harbor in the compose yml, just set image with xxx.harbor.com/project/image:tag which points to harbor instead of docker hub.

**Comment by jeremy-gao** [comment]
@wy65701436  Yes, as you said. I set image with xxx.harbor.com/project/image:tag in the compose yml, eg.:
```
version: "3.2"


services:
  gateway1:
    image: lelai.harbor.com/lelai/php:7.0-swoole 
    networks:
      - swoole_net
    volumes:
      - type: bind
        source: /home/
        target: /home/
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      mode: replicated
      replicas: 2
```

but, when I execute the `docker stack deploy --compose-file docker-66ifuel.yaml test` command,  I got a mistake that couldn't find image,  eg.
```
ID                  NAME                  IMAGE                                   NODE                   DESIRED STATE       CURRENT STATE                     ERROR                              PORTS
lpl84wmdaw9s        test_gateway1.1       lelai.harbor.com/lelai/php:7.0-swoole   docker-machine-host1   Ready               Rejected less than a second ago   "No such image: lelai.harbor.c…"   
yn46jisndsu9         \_ test_gateway1.1   lelai.harbor.com/lelai/php:7.0-swoole   docker-machine-host1   Shutdown            Rejected 2 minutes ago            "No such image: lelai.harbor.c…"   
ywzj38odej6l         \_ test_gateway1.1   lelai.harbor.com/lelai/php:7.0-swoole   docker-machine-host1   Shutdown            Rejected 2 minutes ago            "No such image: lelai.harbor.c…"   
zxw35ri9hkkb         \_ test_gateway1.1   lelai.harbor.com/lelai/php:7.0-swoole   docker-machine-host2   Shutdown            Rejected 2 minutes ago            "No such image: lelai.harbor.c…"   
yk69s6aonu14         \_ test_gateway1.1   lelai.harbor.com/lelai/php:7.0-swoole   docker-machine-host1   Shutdown            Rejected 3 minutes ago            "No such image: lelai.harbor.c…"   

```
