### ISSUE TITLE
Narrow down the authorities and scope of client of Harbor in UAA.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/harbor#3972]
Need to check the doc of UAA and remove the unnecessary authorities.

The goal is to reasonably narrow down the scope, instead of `minimize`

**Comment by reasonerjt** [comment]
```
harbor:
            override: true
            authorized-grant-types: client_credentials,authorization_code,password
            redirect-uri: placeholder
            scope: openid
            authorities: openid,clients.read,clients.secret,uaa.resource,scim.read,scim.write
            secret: secret
```
