### ISSUE TITLE
Failed deployment of Harbor tile causes the pre-delete errand job failed

### ISSUE THREAD

**Issue by steven-zou** [vmware/harbor#4120]
Succeeded
===== 2018-01-24 10:30:32 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.11 update-config cloud /tmp/cloud_config.yml20180124-1434-xn5b69"; Duration: 0s; Exit Status: 0
{"type": "step_finished", "id": "bosh.updating_cloud_config"}
{"type": "step_started", "id": "uaa_config.resetting"}
{"type": "step_finished", "id": "uaa_config.resetting"}
{"type": "step_started", "id": "errands.running.harbor-container-registry-1b868965d192d02f3781.uaa-deregistration"}
===== 2018-01-24 10:30:32 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=30.0.0.11 --deployment=harbor-container-registry-1b868965d192d02f3781 run-errand uaa-deregistration --instance harbor-app/first"
Using environment '30.0.0.11' as client 'ops_manager'

Using deployment 'harbor-container-registry-1b868965d192d02f3781'

Task 11

Task 11 | 10:30:33 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: - Deployment '' doesn't exist
Task 11 | 10:30:33 | Error: - Deployment '' doesn't exist

Task 11 Started  Wed Jan 24 10:30:33 UTC 2018
Task 11 Finished Wed Jan 24 10:30:33 UTC 2018
Task 11 Duration 00:00:00
Task 11 error

Running errand 'uaa-deregistration':
  Expected task '11' to succeed but state is 'error'

**Comment by steven-zou** [comment]
For @frodenas' reference:

'uaa-deregistration' is an errand job defined in the bosh release to unregister the harbor uaa client from the server.

Use the 'colocated' way to run the job at the pre-delete stage. The code is : 
```

job_types:
- name: harbor-app
  resource_label: harbor-app
  templates:
  - name: docker
    release: harbor-container-registry
  - name: harbor
    release: harbor-container-registry
    provides: |
      harbor: {as: harbor_app_link}
      harbor_uaa: {as: harbor_uaa_link}
  - name: uaa-deregistration
    release: harbor-container-registry
    consumes: |
      harbor_uaa_reference: {from: harbor_uaa_link}
  resource_definitions:
```

```
pre_delete_errands:
- name: uaa-deregistration
  colocated: true
  run_default: on
  instances:
    - harbor-app/first
  label: deregister Harbor UAA client
```

If harbor is successfully deployed, then everything will work well.
If failed to deploy, the issue might be appear.

Seems there is no running vm/instance existing for the **colocated** errand job to run if deployment is failed. I'm wondering is it worked as design or there is a possible approach existing to resolve the problem.
