### ISSUE TITLE
docker images pushed to /var/lib/registry but not /storage when deploy harbor on kubernetes

### ISSUE THREAD

**Issue by garyyang85** [vmware/harbor#4200]
I just deployed two habror on two kubernetes env, one works well but the other one works strange.  When I push image to the bad env, it goes to  /var/lib/registry but not the /storage directory. I am sure I have the same cm as below:
**config: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /storage
      cache:
        layerinfo: inmemory
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true**
   could you advice how to debug this? Does harbor use the same docker registry as the official docker registry? Thanks.

**Comment by likunbyl** [comment]
I don't know  the directory you see is from container or host , I think the directory to hold registry files on the host is up to the kubernetes deployment yaml .

**Comment by garyyang85** [comment]
@likunbyl  thanks for you quick response.  The directory hold registry file should controlled by filesystem:
rootdirectory: /storage

in the deployment yaml, we just need to mount the /storage out.   
This is the deployment yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry-apps
    spec:
      containers:
      - name: registry-app
        image: vmware/registry:2.6.2-photon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        - containerPort: 5001
        volumeMounts:
        - name: config
          mountPath: /etc/registry
        - name: storage
          mountPath: /storage
      volumes:
      - name: config
        configMap:
          name: harbor-registry-config
          items:
          - key: config
            path: config.yml
          - key: cert
            path: root.crt
      - name: storage
        persistentVolumeClaim:
          claimName: registry-pvc
```
