### ISSUE TITLE
PKS Clair proxy config

### ISSUE THREAD

**Issue by shinji62** [vmware/harbor#4272]
Using the PKS tile is impossible to configure an HTTP proxy for clair.

We need to manually do it, which means on every bosh update settings will disappear.

For now I need to do

```
sudo su -
monit stop harbor
```

Check with monit summary to be sure harbor is stop

`vi /var/vcap/packages/harbor-app/docker-compose.clair.yml`

Then on the clair configuration just add your proxy
```
clair:
    networks:
      - harbor-clair
    container_name: clair
    image: vmware/clair-photon:v2.0.1-v1.4.0
    restart: always
    cpu_quota: 150000
    depends_on:
      - postgres
    volumes:
      - ./common/config/clair:/config:z
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
    environment: <=== Should ident same a logging just before.
       HTTP_PROXY: "http://my-proxy.com:80"
       HTTPS_PROXY: "https://my-proxy.com:80"
```

`monit start harbor`

I am willing to contribute to the bosh release if needed.
