### ISSUE TITLE
[k8s]由于registry权限不足导致push镜像到harbor失败

### ISSUE THREAD

**Issue by deerjoe** [vmware/harbor#4287]
k8s版本1.8.1
registry版本registry:2.6.2-photon
pv:nfs

push时一直 Retrying in 1 second，最后报received unexpected HTTP status: 500 Internal Server Error

检查registry，log报filesystem: mkdir /storage/docker: permission denied：

> time="2018-02-23T07:49:18.107219771Z" level=error msg="response completed with error" auth.user.name=admin err.code=unknown err.detail="filesystem: mkdir /storage/docker: permission denied" err.message="unknown error" go.version=go1.7.3 http.request.host=***** 

cm

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-registry-config
data:
  config: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /storage
      cache:
        layerinfo: inmemory
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
    http:
      addr: :5000
      secret: placeholder
      debug:
        addr: localhost:5001
    auth:
      token:
        issuer: harbor-token-issuer
        realm: https://*****/service/token
        rootcertbundle: /etc/registry/root.crt
        service: harbor-registry
    notifications:
      endpoints:
        - name: harbor
          disabled: false
          url: http://ui/service/notifications
          timeout: 3000ms
          threshold: 5
          backoff: 1s

```
deploy

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry-apps
    spec:
      containers:
      - name: registry-app
        image: vmware/registry:2.6.2-photon
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        - containerPort: 5001
        volumeMounts:
        - name: config
          mountPath: /etc/registry
        - name: storage
          mountPath: /storage
      volumes:
      - name: config
        configMap:
          name: harbor-registry-config
          items:
          - key: config
            path: config.yml
          - key: cert
            path: root.crt
      - name: storage
        persistentVolumeClaim:
          claimName: registry-pvc
```
