### ISSUE TITLE
upgrading harbor with image storage in gcs (s3, buckets etc)

### ISSUE THREAD

**Issue by nuzz** [vmware/harbor#4387]
I'm attempting to upgrade a few installations of Harbor v1.2.2 to v1.4.0. These Harbor installs are backed by s3/gcs buckets. I have my own version of v1.4.0 Helm chart working however whenever I login to the UI I don't see the repositories/images/tags that are in the bucket in the UI. Is there something harbor specific that's stored in the bucket data that needs to be migrated? I figured I could swap out a newer version of harbor on top of an existing image layer store w/o migrating anything.

```yaml
registry:
    storage:
        gcs:
            keyfile: "/etc/registry/gcs_keyfile.json"
            bucket: "some-bucket-name"
            chunksize: "5242880"
    auth:
        token:
            realm: " https://foo-bar-baz.int.example.com/service/token"
    httpSecret: "secret"
    gcsKeyFile: "gcs_keyfile.json"
    image:
        repository: vmware/registry-photon
        tag: v2.6.2-v1.4.0
    replicas: 1
    pullPolicy: IfNotPresent
```
