### ISSUE TITLE
Allow configuring v4auth for S3 registry storage in Harbor Tile

### ISSUE THREAD

**Issue by shinji62** [vmware/harbor#4399]
In the last version of the Pivotal tile 1.4.1 we can add compatible s3 API object-storage.

But most of Swift version do not support v4 signature, could be nice to be able to add the options to enable or not the v4 signature.

Thanks

**Comment by jessehu** [comment]
@shinji62 do you add "v4auth: false" option ? Any other option you need ?

**Comment by shinji62** [comment]
Well I will prefer having a real choice meaning the real Swift support. But `v4auth: false` should be ok

**Comment by jessehu** [comment]
Here is the options list on https://docs.docker.com/registry/configuration/. Are 'secure: false' and 'encrypt: false' needed in your case ?

```
  s3:
    accesskey: awsaccesskey
    secretkey: awssecretkey
    region: us-west-1
    regionendpoint: http://myobjects.local
    bucket: bucketname
    encrypt: true
    keyid: mykeyid
    secure: true
    v4auth: true
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
    rootdirectory: /s3/object/name/prefix
```
