### ISSUE TITLE
Need to restart to see pushed images

### ISSUE THREAD

**Issue by AlexZeitler** [vmware/harbor#48]
After pushing images to harbor, I have to run ```docker-compose kill``` and ```docker-compose up -d``` to see the new images. Search inside the UI also doesn't find them before restarting.

But I can pull the images using the Docker client without restarting.

**Comment by xiaods** [comment]
i came across this issue, but i wait a moment, it will show the image. maybe something need update period.

**Comment by reasonerjt** [comment]
There's a webhook in ui container to update the images in cache, it should not take more than a few seconds. @AlexZeitler, how long do you have to wait?  Could you attach the config.yml of registry? It's location is harbor/Deploy/config/registry/config.yml

**Comment by AlexZeitler** [comment]
@reasonerjt I have been waiting for about 2 minutes.

`config.yml`:

```yml
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
http:
    addr: :5000
    secret: placeholder
    debug:
        addr: localhost:5001
auth:
  token:
    issuer: registry-token-issuer
    realm: http://localhost/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

notifications:
  endpoints:
      - name: harbor
        disabled: false
        url: http://localhost/service/notifications
        timeout: 500
        threshold: 5
        backoff: 1000
```
