### ISSUE TITLE
[HELM]  Clair unable to authenticate with Postgres

### ISSUE THREAD

**Issue by ArcticSnowman** [vmware/harbor#4816]
Getting for the following error:

```
{"Event":"pgsql: could not open database: pq: password authentication failed for user \"clair\"","Level":"fatal","Location":"main.go:96","Time":"2018-04-27 19:27:26.961615"}
```
I've confirmed that the same password set in 'harbor-clair' configmap and the postgres secret..

Any suggestions?

**Comment by jessehu** [comment]
@ArcticSnowman could you confirm the values in the two blocks are the same? https://github.com/vmware/harbor/blob/master/contrib/helm/harbor/values.yaml#L264-L269 and https://github.com/vmware/harbor/blob/master/contrib/helm/harbor/values.yaml#L291-L294

**Comment by ArcticSnowman** [comment]
Confirm that the password is the same in the two locations in the values.yaml
```
clair:
    postgresPassword: abc123def
---
postgresql:
  postgresUser: clair
  postgresPassword: abc123def
  postgresDatabase: clair
```
Also confirm that the postgres secret has the same password and the clair config map

**Comment by jessehu** [comment]
Your log "pgsql: could not open database: pq" said the database name is 'pq', so I guess you need to set the clair database name like this :

clair:
  postgresPassword: abc123def
  postgresUser: clair
  postgresDatabase: clair

**Comment by ArcticSnowman** [comment]
The full clair section values.yaml is 
```
clair:
  enabled: true
  image:
    repository: vmware/clair-photon
    tag: v2.0.1-v1.4.0
    pullPolicy: IfNotPresent
## The following needs to match the credentials
## in the `postgresql` configuration under the
## `postgresql` namespace below.
  postgresPassword: abc123def
  postgresUser: clair
  postgresDatabase: clair
  volumes:
    pgData:
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 1Gi
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
```
