### ISSUE TITLE
How to set vmware/harbor network?

### ISSUE THREAD

**Issue by fussier** [vmware/harbor#5107]
my docker version is 1.12.0, docker-compose version is 1.21.2, system is Ubuntu 14.04 LTS

Docker uses the default 172.17.0.0/16 subnet for container networking, but my network already uses this subnet,so i change docker0 inet addr to 172.172.45.0/24, but when i install wmware/harbor, i find the harbor components still use 172.17.0.0/16 subnet,harbor.cfg and docker-compose.yml are not changed.

`docker0   Link encap:Ethernet  HWaddr 02:42:29:3d:40:c8  
          inet addr:172.172.45.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:29ff:fe3d:40c8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:10056953 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9632580 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:624341562 (624.3 MB)  TX bytes:591138076 (591.1 MB)`

this is /var/log/harbor/proxy.log:
`Jun  7 00:04:34 172.17.0.1 proxy[13904]: 2018/06/07 00:04:34 [error] 25#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.17.0.7:8080/", host: "127.0.0.1"
Jun  7 00:04:34 172.17.0.1 proxy[13904]: 127.0.0.1 - "GET / HTTP/1.1" 502 166 "-" "curl/7.59.0" 0.000 0.000 .
Jun  7 00:05:04 172.17.0.1 proxy[13904]: 2018/06/07 00:05:04 [error] 27#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.17.0.7:8080/", host: "127.0.0.1"
Jun  7 00:05:04 172.17.0.1 proxy[13904]: 127.0.0.1 - "GET / HTTP/1.1" 502 166 "-" "curl/7.59.0" 0.001 0.001 .
Jun  7 00:05:34 172.17.0.1 proxy[13904]: 2018/06/07 00:05:34 [error] 22#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.17.0.7:8080/", host: "127.0.0.1"`

**Comment by ywk253100** [comment]
The networks Harbor uses are created by docker-compose, so you should configure them in docker compose files.

**Comment by fussier** [comment]
my first thinking is to configure docker compose files, but i can't figure out how to 。。。

this is my docker-compose.yml

proxy:
    image: vmware/nginx-photon:v1.5.1
    container_name: harbor_nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false

and docker network ls 
NETWORK ID          NAME                DRIVER              SCOPE
6196acb46b2b        bridge              bridge              local               
52ee7008dd70        host                host                local               
2837de21a61e        none                null                local

**Comment by ywk253100** [comment]
Please refer to the guide of docker-compose https://docs.docker.com/compose/networking/#specify-custom-networks.

**Comment by itliubin** [comment]
i have the same proboem

**Comment by fagaillard** [comment]
Same issue on OpenStack

A workaround is to modify the docker-compose.yml   file  to add driver_opts
The issue is that the file will be overriden if you re-run the install.sh   script

```
networks:
  harbor:
    external: false
    driver_opts:                         
      com.docker.network.driver.mtu: 1454
  harbor-notary:
    external: false
    driver_opts:                         
      com.docker.network.driver.mtu: 1454
  notary-sig:
    external: false
    driver_opts:                         
      com.docker.network.driver.mtu: 1454
  harbor-clair:
    external: false
    driver_opts:                         
      com.docker.network.driver.mtu: 1454
  harbor-chartmuseum:
    external: false
    driver_opts:                         
      com.docker.network.driver.mtu: 1454
```
