### ISSUE TITLE
Cannot see repositories in project view

### ISSUE THREAD

**Issue by chanjarster** [vmware/harbor#5445]
If you are reporting a problem, please make sure the following information are provided:
1)Version of docker engine and docker-compose.

* Docker version 18.06.0-ce, build 0ffa825
* docker-compose version 1.22.0, build f46880fe

2)Config files of harbor, you can get them by packaging "harbor.cfg" and files in the same directory, including subdirectory.

[harbor.cfg.zip](https://github.com/vmware/harbor/files/2244992/harbor.cfg.zip)

I deploy harbor behind nginx with ssl termination.

3)Log files, you can get them by package the /var/log/harbor/ .

[logs.gz](https://github.com/vmware/harbor/files/2244991/logs.gz)

4) Problem

Harbor version: 1.5.2

I successfuly pushed image to harbor, and I can also pull the image I push, but I cannot see any repositories in project view.

**Comment by aladjadj** [comment]
Hi,
Firstly, is your domain "https://harbor.yourdomain.com"? because you have a lot of mistakes in your journal.

**Comment by chanjarster** [comment]
@aladjadj I replace the actual domain with a fake domain in logs

**Comment by chanjarster** [comment]
@stonezdj I did not install older version of harbor, but I install 1.5.2 harbor several times because of wrong configuration.

I followed   [Managing Harbor's Lifecycle][1] to do the reinstall, and delete the old `/data/database` and `/data/registry` before reinstall.

[1]: https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#managing-harbors-lifecycle

**Comment by ywk253100** [comment]
@chanjarster Please provide the content of common/config/registry/config.yaml.

**Comment by chanjarster** [comment]
@ywk253100 You reminded me, I changed `common/config/registry/config.yml` to make ssl termination work:

```yaml
auth:
  token:
    issuer: harbor-token-issuer
    #realm: http://harbor.yourdomain.com/service/token
    realm: https://harbor.yourdomain.com/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
notifications:
  endpoints:
  - name: harbor
    disabled: false
    #url: http://ui:8080/service/notifications
    url: https://harbor.yourdomain.com/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s
```

I modified `notifications.url` incorrectly to `https://harbor.yourdomain.com`, I changed it back and problem solved.

Thank you guys！
