### ISSUE TITLE
helm config error

### ISSUE THREAD

**Issue by l1b0k** [vmware/harbor#5518]
when deploy harbor in k8s ,Get err
```
error validating data: ValidationError(StatefulSet.spec.template): unknown field "component" in io.k8s.api.core.v1.PodTemplateSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
 The generated file looks like this.

```yaml
# Source: harbor/templates/adminserver/adminserver-ss.yaml
...
  template:
    metadata:
      labels:
        heritage: Tiller
        release: test
        chart: harbor-0.2.0
        app: "harbor"
        component: adminserver
    component: adminserver
    spec:
      containers:
```
It is clearly `component: adminserver ` should not in template

https://github.com/vmware/harbor/blob/c6665934cd6e66af1568215a4801b10f1167ff15/contrib/helm/harbor/templates/adminserver/adminserver-ss.yaml#L18-L24
