### ISSUE TITLE
harbor does not synchronize with emails in ldap

### ISSUE THREAD

**Issue by cherry4477** [vmware/harbor#577]
the environment is openshift

1)the version of docker
Docker version 1.11.2
2)Config files of harbor
```
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    name: ui
  name: ui
spec:
  replicas: 1
  selector:
    name: ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ui
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: rds
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USR
          value: harbor
        - name: MYSQL_PWD
          value: pwd
        - name: REGISTRY_URL
          value: http://registry:5000
        - name: CONFIG_PATH
          value: /etc/ui/app.conf
        - name: HARBOR_REG_URL
          value: registry.dataos.io
        - name: HARBOR_ADMIN_PASSWORD
          value: password
        - name: HARBOR_URL
          value: registry.dataos.io
        - name: AUTH_MODE
          value: ldap_auth
        - name: LDAP_URL
          value: ldap://ldap-lb-:389
        - name: LDAP_BASE_DN
          value: cn=%s,ou=Users,dc=openstack,dc=org
        - name: LOG_LEVEL
          value: debug
        image: 172.30.40.148:5000/harbor/harbor
        imagePullPolicy: Always
        name: ui
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
```
3)Log files:

```
2016-07-21T06:16:32Z [DEBUG] [authenticator.go:52]: Current AUTH_MODE is ldap_auth
2016-07-21T06:16:32Z [DEBUG] [ldap.go:47]: ldapURL:ldap://ldap-lb-1160675848.cn-north-1.elb.amazonaws.com.cn:389
2016-07-21T06:16:32Z [DEBUG] [ldap.go:69]: baseDn:cn=lixw,ou=Users,dc=openstack,dc=org
2016-07-21T06:16:37Z [ERROR] [token.go:82]: Error occurred in UserLogin: LDAP::Bind() error (49) : Invalid credentials
```

we discoverd that:

we changed the email of any user, and looked into the harbor database,the email was not synchronized. 
And when we added the user with the email which was stored and not synchronized in harbor database already,the user could not be added, and hence the user could not login
